### ISSUE TITLE
Issue in displaying the results

### ISSUE THREAD

**Issue by sivaramakrishnan-rajaraman** [aryanmisra/Skin-Lesion-Classifier#1]
Thanks for the awesome repository. I am working with developing a Malaria App. In my case, everything works fine except for the final display of the predictions. The predictions are displayed without the name of the class like this:

Predictions
undefined: 0.465
undefined: 0.331

Please find attached the malaria_classes.js, predict.js and malariapredict.html file. I am not able to find the reason for not getting the classes displayed. Many thanks and looking forward. 

![screenshot from 2018-12-27 09-17-58](https://user-images.githubusercontent.com/45852019/50483216-beb9f080-09b8-11e9-8f07-aa9e584116a6.png)
[malaria_classes.txt](https://github.com/aryanmisra/Skin-Lesion-Classifier/files/2712611/malaria_classes.txt)
[malariapredict.txt](https://github.com/aryanmisra/Skin-Lesion-Classifier/files/2712612/malariapredict.txt)
[predict.txt](https://github.com/aryanmisra/Skin-Lesion-Classifier/files/2712613/predict.txt)

**Comment by maltseasy** [comment]
Hey Sivarama, 

I apologize for the late reply but I'd love to help you out with this.
It'd be great if you could send me all of the project files that you're working with here, it'll help me a lot with debugging!

**Comment by sivaramakrishnan-rajaraman** [comment]
Hi Aryan,
Many thanks for your immediate response. I found a solution myself. I had an issue with the final prediction layer of my model which I rectified and now the app is working fine. Many thanks once again.
Best,
SR

**Comment by maltseasy** [comment]
Hey Sivarama, 

I'm glad you were able to solve the issue. I'd love to stay updated on your work, I find it really interesting! Please feel free to reach out to me if you have any other questions or comments.

Thanks,
Aryan
